### ISSUE TITLE
Installation du code pour le caroussel

### ISSUE THREAD

**Issue by AlexDmr** [dsaadesignv/MediaCenter#2]
Dans un terminal (ou powershell pour windows), se placer dans le répertoire Angular 2 : 
npm install --save     @types/jquery     jquery      bootstrap

Puis, dans le fichier main.ts, après les lignes qui débttent par import .., ajoutez :  
import "node_modules/jquery/dist/jquery.min.js";
import "node_modules/bootstrap/dist/js/bootstrap.min.js";

**Comment by jbjoatton** [comment]
Ça ne marche pas… jQuery n'est pas chargé
`core.umd.js:3004 EXCEPTION: Error in ts/Components/m1m-multimedia-manager.html:58:6 caused by: $ is not a function`
Une idée ?

**Comment by AlexDmr** [comment]
Ca a du cracher dans gulp avant ça, qu'est ce que dit GULP ?

**Comment by AlexDmr** [comment]
bien vérifier que le fichier tsconfig.js

{
  "compilerOptions": {
    "target": "es6",
    "module": "system",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "removeComments": false,
    "noImplicitAny": false,
    "suppressImplicitAnyIndexErrors": true,
    "baseUrl": "."
  },
  "exclude": [
    "node_modules"
  ]
}

**Comment by AlexDmr** [comment]
Mettre au début du fichier m1m-multimedia-manager

import * as $ from "jquery";
console.log( "$ =", $);

**Comment by jbjoatton** [comment]
Pas d'erreur GULP, les fichiers sont bien à jour

**Comment by AlexDmr** [comment]
Bon j'ai fait une petite mise à jour, apparamment il y avait un problème de lien pour socket.io.client.... étrange...
DOnc faire un git pull

**Comment by jbjoatton** [comment]
Toujours la même erreur au click sur un media après mise à jour : 
`> core.umd.js:3004 EXCEPTION: Error in ts/Components/m1m-multimedia-manager.html:58:6 caused by: $ is not a function`
`> ORIGINAL EXCEPTION: $ is not a function`

**Comment by AlexDmr** [comment]
Ok je n'avais pas saisie que ça se produisait au click sur un média... je vais creuser ça du coup.

**Comment by AlexDmr** [comment]
Une rustine pour avancer (avant que je ne corrige vraiment: 
remplacer
import * as $ from "jquery";

par :  
declare var $;

**Comment by AlexDmr** [comment]
ok c'est corrigé, bien mettre à jour le repo (git pull) puis faire un npm install et un gulp

**Comment by jbjoatton** [comment]
Parfait, tout fonctionne !
